config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :sessions, :passwords]
  as :user do
    get  "signup" => "devise/registrations#new",    as: :signup
    get  "signup" => "devise/registrations#new",    as: :new_user_registration
    post "signup" => "devise/registrations#create", as: :user_registration

    get  "signin" => "devise/sessions#new",     as: :signin
    get  "signin" => "devise/sessions#new",     as: :new_user_session
    post "signin" => "devise/sessions#create",  as: :user_session
    get  "logout" => "devise/sessions#destroy", as: :logout

    get  "password/reset"  => "devise/passwords#new",    as: :reset_password
    get  "password/reset"  => "devise/passwords#new",    as: :new_user_password
    post "password/reset"  => "devise/passwords#create", as: :user_password
    put  "password/reset"  => "devise/passwords#update"
    get  "password/update" => "devise/passwords#edit",   as: :edet_password
    get  "password/update" => "devise/passwords#edit",   as: :edit_user_password
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      def v1_one(name, *actions, **options, &block)
        actions = [:index, :show, :create, :update, :destroy] if actions.empty?
        resource name, options.merge(only: actions), &block
      end

      def v1_many(name, *actions, **options, &block)
        actions = [:index, :show, :create, :update, :destroy] if actions.empty?
        resources name, options.merge(only: actions), &block
      end

      v1_many :forms
    end
  end

  get "home"       => "pages#show", as: :home, id: :home
  get "app(*path)" => "pages#show", as: :app,  id: :app

  authenticated :user do
    root to: redirect("app"), as: :authenticated_root, id: :app
  end

  root to: "pages#show", id: :home
end

app/models/form.rb
class Form
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  belongs_to :user, index: true

  validates :name, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email,                  type: String, default: ""
  field :encrypted_password,     type: String, default: ""
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at,    type: Time
  field :confirmation_token,     type: String
  field :confirmed_at,           type: DateTime
  field :confirmation_sent_at,   type: DateTime

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  has_many :forms
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Metal
  include AbstractController::Rendering
  include AbstractController::Callbacks
  include ActionController::RequestForgeryProtection
  include ActionController::Helpers
  include ActionController::Head
  include ActionController::Redirecting
  include ActionController::Serialization
  include ActionController::StrongParameters
  include ActionController::Rescue
  include ActionController::ConditionalGet
  include ActionController::Rendering
  include ActionController::Renderers::All
  include ActionController::Instrumentation
  include ActionController::ParamsWrapper
  include Devise::Controllers::Helpers
  include Api::V1::ExceptionHandling

  # protect_from_forgery with: :null_session

  wrap_parameters format: [:json]
end

app/controllers/api/v1/forms_controller.rb
class Api::V1::FormsController < Api::V1::ApplicationController
  before_action :authenticate_user!

  def index
    render json: current_user.forms
  end

  def show
    render json: current_user.forms.find(params[:id])
  end

  def create
    render json: current_user.forms.create!(form_params), status: :created
  end

  def update
    form = current_user.forms.find(params[:id]).tap do |event|
      form.update_attributes! form_params
    end

    render json: form
  end

  def destroy
    current_user.forms.find(params[:id]).destroy

    head :no_content
  end

protected

  def form_params
    params.require(:form).permit :name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def after_sign_in_path_for(resource)
    app_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/concerns/api/v1/exception_handling.rb
module Api::V1::ExceptionHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActionController::ParameterMissing, with: :render_422
    rescue_from Mongoid::Errors::MongoidError,      with: :render_422
    rescue_from Mongoid::Errors::DocumentNotFound,  with: :render_404
  end

protected

  def render_error(object, status)
    errors = object.try(:errors) || object.try(:message) || object.try(:to_s)
    render json: errors.to_json, status: status
  end

  def render_400(ex)
    render_error ex, :bad_request
  end

  def render_401(ex)
    render_error ex, :unauthorized
  end

  def render_404(ex)
    render_error ex, :not_found
  end

  def render_422(ex)
    render_error ex, :unprocessable_entity
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout :determine_layout

  def show
    render "pages/#{params[:id]}"
  end

protected

  def determine_layout
    if %(app).include? params[:id].to_s
      "application"
    else
      "static"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path, options={})
    doc = Nokogiri::HTML::DocumentFragment.parse(File.read(AssetsManifest.find_asset(path)).force_encoding("UTF-8"))
    svg = doc.at_css "svg"

    if options[:class].present?
      svg["class"] = options[:class]
    end

    raw doc
  end
end

app/helpers/mail_helper.rb
module MailHelper
end

app/views/layouts/application.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Figure</title>

    <base href="/">

    <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
    <%= csrf_meta_tags %>

    <% javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>

    <!-- libs -->

    <%= javascript_include_tag "system.src.js" %>

    <script>
      System.config({
        baseURL: '/assets',
        defaultJSExtensions: true
      });
    </script>

    <%= javascript_include_tag "angular2.dev.js" %>
    <%= javascript_include_tag "router.dev.js" %>
    <%= javascript_include_tag "http.dev.js" %>

    <!-- assets -->

    <%= javascript_include_tag "init" %>
  </head>

  <body class="app">
    <%= yield %>
  </body>
</html>

app/views/layouts/mail.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><%= @subject %></title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/static.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Figure</title>

    <base href="/">

    <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
  </head>

  <body class="static">
    <%= yield %>
  </body>
</html>

app/views/pages/app.erb
<app>Loading...</app>

app/views/pages/home.erb
<main class="static home">
  <h1>Home is where the heart was.</h1>

  <div>
    <% if user_signed_in? %>
      <%= link_to "Dashboard", app_path %> |
      <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to "Sign In", signin_path %>
    <% end %>
  <div>
</main>